import React from "react";
import "./userPicture.css";
import image from "../../../home/components/stories/img/img-test.jpg";
export default function UserPicture(){
    return (
        <div className="user-picture-container">
            <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
                <img 
                src={image} 
                alt="Loading..." 
                className="user-picture"
            />
       
                
            
      
        </div>
    );
}